M48
; DRILL file {KiCad (6.0.9)} date Thu Dec 22 23:35:37 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-22T23:35:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X4.9126Y-4.1528
X5.3126Y-4.1528
X6.1189Y-4.1575
X6.5189Y-4.1575
T2
X5.1126Y-4.1528
X6.3189Y-4.1575
T0
M30
